---
#
# playbook: ansible-scala
# notes: scala playbook
# depends:
#   - ansible-java
#

- hosts: all
  sudo: True
  tasks:
  vars:
    version: "0.1.0"
    scala_version: "2.10.3"
    scala_version_name: "scala-{{scala_version}}"
    scala_archive_file: "{{scala_version_name}}.tgz"
    scala_download_url: "http://www.scala-lang.org/files/archive/{{scala_archive_file}}"

    lib_path: "/usr/share/scala"
    lib_path_target: "{{lib_path}}/{{scala_version_name}}"
    link_target: "/usr/bin"

  tasks:
    - name: Create scala lib dir
      file: path={{lib_path}} state=directory

    - name: Clean existing Scala {{scala_version_name}} if it exists
      file: path={{lib_path_target}} state=absent

    - name: Download scala v{{scala_version}}
      get_url: url={{scala_download_url}} 
        dest=/tmp/{{scala_archive_file}}
        force=no

    - name: Unpack Scala
      command: tar -xvf {{scala_archive_file}} chdir=/tmp/

    - name: Move (by force) Scala to lib
      command: mv /tmp/{{scala_version_name}} {{lib_path_target}} chdir=/tmp/

    - name: Link scala
      command: sudo ln -sf {{lib_path_target}}/bin/scala {{link_target}}

    - name: Link scalac
      command: sudo ln -sf {{lib_path_target}}/bin/scalac {{link_target}}

    - name: Link fsc
      command: sudo ln -sf {{lib_path_target}}/bin/fsc {{link_target}}

    - name: Link sbaz
      command: sudo ln -sf {{lib_path_target}}/bin/sbaz {{link_target}}

    - name: Link sbaz-setup
      command: sudo ln -sf {{lib_path_target}}/bin/sbaz-setup {{link_target}}

    - name: Link scaladoc
      command: sudo ln -sf {{lib_path_target}}/bin/scaladoc {{link_target}}

    - name: Link scalap
      command: sudo ln -sf {{lib_path_target}}/bin/scalap {{link_target}}
